server:
  port: 8082

management:
  endpoint:
    health:
      probes:
        enabled: true
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: true
spring:
  profiles:
    active: chaos-monkey
  application:
    name: fashion-bestseller
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

eureka:
  client:
    enabled: false