management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8070
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

eureka:
  client:
    enabled: false