server:
  port: 8081


# Init Chaos Monkey for Spring Boot by profile
spring:
  profiles:
    active: chaos-monkey
  application:
    name: toys-bestseller
  cloud:
    kubernetes:
      enabled: false


# Configure Chaos Monkey - enabled = false
chaos:
  monkey:
#    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      level: 3
      latency-active: true

# Spring Boot Actuator Endpoint Chaos Monkey for Spring Boot
management:
  endpoint:
    chaosmonkey:
      enabled: true
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: configserver:http://spring-cloud-kubernetes-configserver:8888

eureka:
  client:
    enabled: false
